# Generated by Django 5.1.1 on 2024-09-25 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='item',
            name='in_out',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='Unnamed Item', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(default='Unnamed Item', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_sku', models.ForeignKey(default='Unnamed Item', on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('destination', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_sku', models.ForeignKey(default='Unnamed Item', on_delete=django.db.models.deletion.CASCADE, to='main.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
