# Generated by Django 5.1.1 on 2024-09-25 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='product_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='supplier',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='product_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
